const films = [
     evident: [
         {
      id: "sarah_bellows",
      title: "Histoires Terrifiantes à Raconter dans le Noir",
      answers: ["histoires terrifiantes", "scary stories to tell in the dark", "histoires terrifiantes à raconter dans le noir"],
      hint: "Un livre maudit qui écrit ses propres histoires...",
      object: "book",
      color: 0x8b0000,
      points: 100,
    },
    {
      id: "bird_box",
      title: "Bird Box",
      answers: ["bird box"],
      hint: "Ne jamais ouvrir les yeux dehors...",
      object: "blindfold",
      color: 0xf5f5dc,
      points: 100,
    },
    {
      id: "mercredi",
      title: "Mercredi",
      answers: ["mercredi", "wednesday"],
      hint: "Une jeune fille sombre dans une académie étrange...",
      object: "hand",
      color: 0x2d5a27,
      points: 100,
    },
    {
      id: "stranger_things",
      title: "Stranger Things",
      answers: ["stranger things"],
      hint: "Une petite ville, un monde à l'envers...",
      object: "lights",
      color: 0xff6600,
      points: 100,
    },
    {
      id: "frankenstein",
      title: "Frankenstein",
      answers: ["frankenstein"],
      hint: "Créé par la science, rejeté par les hommes...",
      object: "monster",
      color: 0x4a7c59,
      points: 100,
    },
],
     facile: [
         {
      id: "army_of_dead",
      title: "Army of the Dead",
      answers: ["army of the dead", "army of dead"],
      hint: "Un coffre-fort au milieu d'une ville de zombies...",
      object: "safe",
      color: 0x8b7355,
      points: 200,
    },
    {
      id: "troll",
      title: "Troll",
      answers: ["troll"],
      hint: "Une créature de pierre réveillée dans les montagnes norvégiennes...",
      object: "troll",
      color: 0x696969,
      points: 200,
    },
    {
        id: "sous_la_seine",
      title: "Sous la Seine",
      answers: ["sous la seine", "under paris"],
      hint: "Un prédateur dans la capitale française...",
      object: "fin",
      color: 0x1a5276,
      points: 200,
    },
    {
        id: "anaconda",
      title: "Anaconda",
      answers: ["anaconda"],
      hint: "Le plus grand prédateur de la jungle amazonienne...",
      object: "snake",
      color: 0x2d5016,
      points: 200,
    },
    {
        id: "sharknado",
      title: "Nature Prédatrice",
      answers: ["nature predatrice", "nature prédatrice", "sharknado"],
      hint: "Quand les tornades rencontrent les requins...",
      object: "tornado",
      color: 0x4169e1,
      points: 200,
    },
],
      moyen: [
        {
      id: "sans_bruit",
      title: "Sans un Bruit",
      answers: ["sans un bruit", "a quiet place"],
      hint: "Le moindre son peut être fatal...",
      object: "silence",
      color: 0xd4af37,
      points: 300,
    },
    {
        id: "day_shift",
      title: "Day Shift",
      answers: ["day shift"],
      hint: "Un chasseur de vampires à Los Angeles...",
      object: "vampire",
      color: 0x4b0082,
      points: 300,
    },
    {

      id: "the_silence",
      title: "The Silence",
      answers: ["the silence", "le silence"],
      hint: "Des créatures aveugles qui chassent au son...",
      object: "vesp",
      color: 0x8b8682,
      points: 300,
    },
    {
         id: "nobody_sleeps",
      title: "Nobody Sleeps in the Woods Tonight",
      answers: ["nobody sleeps in the woods tonight", "nobody sleeps"],
      hint: "Deux silhouettes identiques dans les bois polonais...",
      object: "twins",
      color: 0x3d1c02,
      points: 300,
    },
    {
      id: "le_rituel",
      title: "Le Rituel",
      answers: ["le rituel", "the ritual"],
      hint: "Un dieu nordique oublié rôde dans la forêt suédoise...",
      object: "antler",
      color: 0x1c3a1c,
      points: 300,
    },

  ],
  difficile: [
    

      ]
         

